version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: benchmark_postgres
    environment:
      POSTGRES_USER: benchmark_user
      POSTGRES_PASSWORD: benchmark_password
      POSTGRES_DB: benchmark_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U benchmark_user -d benchmark_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:16-alpine
    container_name: benchmark_postgres_test
    environment:
      POSTGRES_USER: benchmark_user
      POSTGRES_PASSWORD: benchmark_password
      POSTGRES_DB: benchmark_test_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U benchmark_user -d benchmark_test_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  postgres_test_data:
